### ISSUE TITLE
Allow setting a custom name for migrations table

### ISSUE THREAD

**Issue by ntrrg** [maragudk/migrate#11]
I think it would be useful and more flexible. Maybe with some [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) or just another `New*` function.

* Just an exported field:

```go
type Migrator struct {
	DB *sql.DB
	FS fs.FS
	Table string
}
```

```go
m := New(db, migrations)
m.Table = "migrate_inator"
```

* With another `New*` function:

```go
type Migrator struct {
	DB *sql.DB
	FS fs.FS
	table string
}

// New Migrator with default options.
func New(db *sql.DB, fs fs.FS) *Migrator {
	return &Migrator{
		DB: db,
		FS: fs,
		table: "migrate",
	}
}

func NewWithTable(db *sql.DB, fs fs.FS, table string) *Migrator {
	return &Migrator{
		DB: db,
		FS: fs,
		table: table,
	}
}
```

```go
m := NewWithTable(db, migrations, "migrate_inator")
```

* With a `Config` struct:

```go
type Config struct {
	DB *sql.DB
	FS fs.FS
	Table string
}

type Migrator struct {
	DB *sql.DB
	FS fs.FS
	table string
}

// New Migrator with default options.
func New(db *sql.DB, fs fs.FS) *Migrator {
	return NewWithConfig(Config{
		DB: db,
		FS: fs,
		Table: "migrate",
	})
}

func NewWithConfig(cfg Config) *Migrator {
	return &Migrator{
		DB: cfg.DB,
		FS: cfg.FS,
		table: cfg.Table,
	}
}
```

```go
m := NewWithConfig(Config{
	DB: db,
	FS: migrations,
	Table: "migrate_inator"
})
```

* With functional options:

```go
type Migrator struct {
	DB *sql.DB
	FS fs.FS
	table string
}

type Option func(*Migrator)

// New Migrator with default options.
func New(db *sql.DB, fs fs.FS, options ...Option) *Migrator {
	m := &Migrator{
		DB: db,
		FS: fs,
		table: "migrate",
	}

	for _, opt := range options {
		opt(m)
	}

	return m
}

func WithTable(table string) Option {
	return func(m *Migrator) {
		m.table = table
	}
}
```

```go
m := New(db, migrations, WithTable("migrate_inator"))
```

**Comment by markuswustenberg** [comment]
@ntrrg thank you for the suggestion. I think it makes sense to have this. I'll think about the approach I like the most and probably implement it. 😊

**Comment by markuswustenberg** [comment]
@ntrrg out of curiosity, why would you want to change the table name?

**Comment by ntrrg** [comment]
Great, let me know if you need help. The good thing about the last two is you can implement new features without changing functions signatures.

To provide flexibility, some people may have a `migrations` table already. Or you may want to run multiple migrators (dangerous, but useful).

**Comment by markuswustenberg** [comment]
Because the library is still in v0, I opted to break compatibility and have `New` take an `Options` struct. The convenience functions are still the same.

This is now implemented, thanks for the suggestion @ntrrg. 😊

**Comment by ntrrg** [comment]
Amazing, thanks for your work!
