### ISSUE TITLE
Permit custom migration table name to contain '.'

### ISSUE THREAD

**Issue by mirkoperillo** [maragudk/migrate#23]
Currently it is impossible to create a migration table with name `master.migrations` for example.
The reason is the regexp that check the name
https://github.com/maragudk/migrate/blob/507b57a50cdcbdaacc8cb3d0a4b0c5fb67187d1a/migrate.go#L18

This can be useful when a Postgresql DB contains multiple schemas and you want to create migration table in a specific one.

I suggest to add '.' as a valid character 
`tableMatcher = regexp.MustCompile(`^[\w\\.]+$`)`

**Comment by markuswustenberg** [comment]
Hey @mirkoperillo. That sounds reasonable. Would you like to submit a PR along with a test?

**Comment by mirkoperillo** [comment]
@markuswustenberg yes, I'm interested.
I'm going to provide a PR asap

**Comment by markuswustenberg** [comment]
@mirkoperillo Thanks again. 😊 I've just released v0.4.2 where your change is included.
