### ISSUE TITLE
Expose getCurrentVersion function

### ISSUE THREAD

**Issue by mirkoperillo** [maragudk/migrate#27]
https://github.com/maragudk/migrate/blob/b86d7a9b2a9cf1e643280287337756db6bdb96af/migrate.go#L293

In some scenario a public usage of this function can be interesting, for example for a migration tool based on your library.

I can propose a PR about this, if the behavior is considered useful.

**Comment by markuswustenberg** [comment]
Hey @mirkoperillo, thanks for your suggestion. I would rather like to keep the API small and simple. Since it's not something a regular user of the library would use, I think the method is best kept private. 😊
